import type { Metadata } from "next";
import { PT_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/main.scss";
import { Header } from "@/components/header/header";

const ptMono = PT_Mono({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerData = {
  brand: {
    title: 'Letnull19A Portfolio',
    href: '#cases',
  },
  items: [
    { id: 'cases', label: 'Cases', href: '#cases' },
    { id: 'about', label: 'About', href: '#about' },
    { id: 'process', label: 'Process', href: '#process' },
    { id: 'ask', label: 'Ask', href: '#ask' },
    { id: 'articles', label: 'Articles', href: '#articles' },
  ],
  action: {
    label: 'Contact me',
    href: '#contact',
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${ptMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
